// Generated by CoffeeScript 1.12.7

/*
PDFEscape - escape PDF "Name objects" or "Strings"
 */

(function() {
  var PDFEscape;

  PDFEscape = (function() {
    function PDFEscape() {}

    PDFEscape.escapeString = function(s) {
      var escapable, escapableRe;
      escapableRe = /[\n\r\t\b\f\(\)\\]/g;
      escapable = {
        '\n': '\\n',
        '\r': '\\r',
        '\t': '\\t',
        '\b': '\\b',
        '\f': '\\f',
        '\\': '\\\\',
        '(': '\\(',
        ')': '\\)'
      };
      return s.replace(escapableRe, function(c) {
        return escapable[c];
      });
    };

    PDFEscape.escapeName = function(s) {
      var escapable, escapableRe;
      escapableRe = /\//g;
      escapable = {
        '/': '#2F'
      };
      return s.replace(escapableRe, function(c) {
        return escapable[c];
      });
    };

    return PDFEscape;

  })();

  module.exports = PDFEscape;

}).call(this);
